// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://woecdpxjlxfnuqvlpchf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndvZWNkcHhqbHhmbnVxdmxwY2hmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3MjMxMDYsImV4cCI6MjA1NDI5OTEwNn0.RU9ehtq8dyT3oe7NW_eYsXaoSgCrHGbt57CHIGM4808";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);